name: 'gha-dotnet-hello-world'
author: 'taori@users.noreply.github.com'
description: 'TODO Description'
branding:
  icon: book-open
  color: purple
inputs:
  workspace:
    description: 'path of workspace'
    required: true
outputs: 
  message: 
    description: "message from the runner"
runs:
  using: 'docker'
  # https://learn.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action#performance-improvements
  image: 'docker://ghcr.io/taori/gha-dotnet-hello-world:v0.1.6'
  args:
    - '-w'
    - ${{ inputs.workspace }}