global using System.Globalization;
global using System.Text;
global using System.Web;
global using CommandLine;
global using DotnetGithubActionHelloWorld;
global using Markdown;
global using Microsoft.CodeAnalysis;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.FileSystemGlobbing;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using static CommandLine.Parser;